### ISSUE TITLE
robin_hood.h:2012:13: error: attempt to free a non-heap object 'fm' [-Werror=free-nonheap-object]

### ISSUE THREAD

**Issue by zenfey** [martinus/robin-hood-hashing#50]
https://github.com/martinus/robin-hood-hashing/blob/813dadddc58417385bf7dff9fb2e1f5939c23598/src/include/robin_hood.h#L2012

COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

**Comment by martinus** [comment]
Hi, thanks for reporting! I could reproduce this warning with g++-7 (it works with g++5, g++9.2, clang++6, clang++9...) and have modified the code so this error doesn't happen.
